name: photo_editor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  blur: ^4.0.2
  colorfilter_generator: ^0.0.8
  crop_image: ^1.0.16
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  image_picker: ^1.2.0
  pixel_color_picker: ^1.0.0
  provider: ^6.1.5+1
  screenshot: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/textures/
    - assets/images/
