name: photo_editor
description: "App for photo editing"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  blur: ^4.0.2
  colorfilter_generator: ^0.0.8
  crop_image: ^1.0.16
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  image: ^4.5.4
  image_gallery_saver_plus: ^4.0.1
  image_picker: ^1.2.0
  lindi_sticker_widget: ^0.1.1
  matrix_gesture_detector: ^0.2.0-nullsafety.1
  painter: ^2.0.0
  provider: ^6.1.5+1
  screenshot: ^3.0.0
  text_editor: ^0.7.0
  widget_mask: ^1.0.0+0
  url_launcher: ^6.3.0
  file_picker: ^8.1.4
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  package_info_plus: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  background_color_android: "#ffffff"
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  image_path: "assets/images/logo.png"

  # Для Windows
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48

  # Для Linux
  linux:
    generate: true
    image_path: "assets/images/logo.png"

  # Для Web
  web:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/textures/
    - assets/images/
    - assets/stickers/

  fonts:
    - family: AlexBrush
      fonts:
        - asset: 'fonts/AlexBrush-Regular.ttf'
    - family: Allura
      fonts:
        - asset: 'fonts/Allura-Regular.ttf'
    - family: Arizonia
      fonts:
        - asset: 'fonts/Arizonia-Regular.ttf'
    - family: GrandHotel
      fonts:
        - asset: 'fonts/GrandHotel-Regular.ttf'
    - family: GreatVibes
      fonts:
        - asset: 'fonts/GreatVibes-Regular.ttf'
    - family: Lobster
      fonts:
        - asset: 'fonts/Lobster-Regular.ttf'
    - family: OpenSans
      fonts:
        - asset: 'fonts/OpenSans-Regular.ttf'
    - family: Oswald
      fonts:
        - asset: 'fonts/Oswald-Regular.ttf'
    - family: Pacifico
      fonts:
        - asset: 'fonts/Pacifico-Regular.ttf'
    - family: Roboto
      fonts:
        - asset: 'fonts/Roboto-Regular.ttf'
    - family: WindSong
      fonts:
        - asset: 'fonts/WindSong-Regular.ttf'
    - family: Rubik
      fonts:
        - asset: 'fonts/Rubik-Regular.ttf'
